//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Reservation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Reservation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Reservation", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AmountMode.
        /// </summary>
        internal static string AmountMode {
            get {
                return ResourceManager.GetString("AmountMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure Select This Chair?.
        /// </summary>
        internal static string AreYouSureSelectThisChair {
            get {
                return ResourceManager.GetString("AreYouSureSelectThisChair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure Save And Close?.
        /// </summary>
        internal static string AreYouSureSelectThisChairAndSaveandClose {
            get {
                return ResourceManager.GetString("AreYouSureSelectThisChairAndSaveandClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssignNumberLeft.
        /// </summary>
        internal static string AssignNumberLeft {
            get {
                return ResourceManager.GetString("AssignNumberLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssignNumberRight.
        /// </summary>
        internal static string AssignNumberRight {
            get {
                return ResourceManager.GetString("AssignNumberRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssignNumberToDown.
        /// </summary>
        internal static string AssignNumberToDown {
            get {
                return ResourceManager.GetString("AssignNumberToDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssignNumberToUp.
        /// </summary>
        internal static string AssignNumberToUp {
            get {
                return ResourceManager.GetString("AssignNumberToUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chair Informations.
        /// </summary>
        internal static string ChairInformation {
            get {
                return ResourceManager.GetString("ChairInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChairType.
        /// </summary>
        internal static string ChairType {
            get {
                return ResourceManager.GetString("ChairType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChairTypeList.
        /// </summary>
        internal static string ChairTypeList {
            get {
                return ResourceManager.GetString("ChairTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChairTypeNew.
        /// </summary>
        internal static string ChairTypeNew {
            get {
                return ResourceManager.GetString("ChairTypeNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        internal static string Design {
            get {
                return ResourceManager.GetString("Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to draw.
        /// </summary>
        internal static string draw {
            get {
                return ResourceManager.GetString("draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to erase.
        /// </summary>
        internal static string erase {
            get {
                return ResourceManager.GetString("erase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall.
        /// </summary>
        internal static string Hall {
            get {
                return ResourceManager.GetString("Hall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall List.
        /// </summary>
        internal static string HallList {
            get {
                return ResourceManager.GetString("HallList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HallMode.
        /// </summary>
        internal static string HallMode {
            get {
                return ResourceManager.GetString("HallMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall Photo.
        /// </summary>
        internal static string HallPhoto {
            get {
                return ResourceManager.GetString("HallPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than the number of seats you&apos;ve selected The number of times you are permitted to.
        /// </summary>
        internal static string Morethathenumberofseatsyouselected {
            get {
                return ResourceManager.GetString("Morethathenumberofseatsyouselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Design.
        /// </summary>
        internal static string NewDesign {
            get {
                return ResourceManager.GetString("NewDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Hall.
        /// </summary>
        internal static string NewHall {
            get {
                return ResourceManager.GetString("NewHall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        internal static string NumberDirection {
            get {
                return ResourceManager.GetString("NumberDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Direction Horizontal.
        /// </summary>
        internal static string NumberDirectionHorizontal {
            get {
                return ResourceManager.GetString("NumberDirectionHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Direction Vertical.
        /// </summary>
        internal static string NumberDirectionVertical {
            get {
                return ResourceManager.GetString("NumberDirectionVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberMode.
        /// </summary>
        internal static string NumberMode {
            get {
                return ResourceManager.GetString("NumberMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        internal static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Minimum  Number.
        /// </summary>
        internal static string PleaseEnterMinNumber {
            get {
                return ResourceManager.GetString("PleaseEnterMinNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select ChairType.
        /// </summary>
        internal static string PleaseSelectChairType {
            get {
                return ResourceManager.GetString("PleaseSelectChairType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Direction.
        /// </summary>
        internal static string PleaseSelectDirection {
            get {
                return ResourceManager.GetString("PleaseSelectDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Status.
        /// </summary>
        internal static string PleaseSelectStatus {
            get {
                return ResourceManager.GetString("PleaseSelectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait Server Is Processing.
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        internal static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusMode.
        /// </summary>
        internal static string StatusMode {
            get {
                return ResourceManager.GetString("StatusMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Chair Reserved By Person User Can not change Status.
        /// </summary>
        internal static string ThisChairReserved {
            get {
                return ResourceManager.GetString("ThisChairReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This number is already registered.
        /// </summary>
        internal static string Thisnumberisalreadyregistered {
            get {
                return ResourceManager.GetString("Thisnumberisalreadyregistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Selected Chair Information.
        /// </summary>
        internal static string YourSelectedChairInformation {
            get {
                return ResourceManager.GetString("YourSelectedChairInformation", resourceCulture);
            }
        }
    }
}
