//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebDesign {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebDesign() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.WebDesign", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agencies.
        /// </summary>
        internal static string Agencies {
            get {
                return ResourceManager.GetString("Agencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AverageSlideId.
        /// </summary>
        internal static string AverageSlideId {
            get {
                return ResourceManager.GetString("AverageSlideId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Award.
        /// </summary>
        internal static string Award {
            get {
                return ResourceManager.GetString("Award", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BigSlideId.
        /// </summary>
        internal static string BigSlideId {
            get {
                return ResourceManager.GetString("BigSlideId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate.
        /// </summary>
        internal static string Certificate {
            get {
                return ResourceManager.GetString("Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container.
        /// </summary>
        internal static string Container {
            get {
                return ResourceManager.GetString("Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The conference is disabled at this address.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FooterId.
        /// </summary>
        internal static string FooterId {
            get {
                return ResourceManager.GetString("FooterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeaderId.
        /// </summary>
        internal static string HeaderId {
            get {
                return ResourceManager.GetString("HeaderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html.
        /// </summary>
        internal static string Html {
            get {
                return ResourceManager.GetString("Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstallPath.
        /// </summary>
        internal static string InstallPath {
            get {
                return ResourceManager.GetString("InstallPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IntroPage.
        /// </summary>
        internal static string IntroPage {
            get {
                return ResourceManager.GetString("IntroPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnify.
        /// </summary>
        internal static string Magnify {
            get {
                return ResourceManager.GetString("Magnify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max News Show.
        /// </summary>
        internal static string MaxNewsShow {
            get {
                return ResourceManager.GetString("MaxNewsShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiniSlideId.
        /// </summary>
        internal static string MiniSlideId {
            get {
                return ResourceManager.GetString("MiniSlideId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Resource.
        /// </summary>
        internal static string NewResource {
            get {
                return ResourceManager.GetString("NewResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference setting is not done, please go to the settings page.
        /// </summary>
        internal static string NotConfig {
            get {
                return ResourceManager.GetString("NotConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The conference is not defined on the route.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The man&apos;s forum is not registered at this address.
        /// </summary>
        internal static string NotRegistered {
            get {
                return ResourceManager.GetString("NotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName.
        /// </summary>
        internal static string PersonFullName {
            get {
                return ResourceManager.GetString("PersonFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Config This WebSite.
        /// </summary>
        internal static string PleaseConfigThisWebSite {
            get {
                return ResourceManager.GetString("PleaseConfigThisWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set path WebSite on the Management WebSite.
        /// </summary>
        internal static string PleasesetpathWebSiteontheManagementWebSite {
            get {
                return ResourceManager.GetString("PleasesetpathWebSiteontheManagementWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource.
        /// </summary>
        internal static string Resource {
            get {
                return ResourceManager.GetString("Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource List.
        /// </summary>
        internal static string ResourceList {
            get {
                return ResourceManager.GetString("ResourceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rial.
        /// </summary>
        internal static string Rial {
            get {
                return ResourceManager.GetString("Rial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Products.
        /// </summary>
        internal static string SelectedProducts {
            get {
                return ResourceManager.GetString("SelectedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Map.
        /// </summary>
        internal static string Sitemap {
            get {
                return ResourceManager.GetString("Sitemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions.
        /// </summary>
        internal static string suggestions {
            get {
                return ResourceManager.GetString("suggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CellPhone.
        /// </summary>
        internal static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserFor.
        /// </summary>
        internal static string UseFor {
            get {
                return ResourceManager.GetString("UseFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        internal static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebSite.
        /// </summary>
        internal static string WebSite {
            get {
                return ResourceManager.GetString("WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebSite Archive News.
        /// </summary>
        internal static string WebSiteArchiveNews {
            get {
                return ResourceManager.GetString("WebSiteArchiveNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebSite Gallery.
        /// </summary>
        internal static string WebSiteGallery {
            get {
                return ResourceManager.GetString("WebSiteGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebSite Is Disable.
        /// </summary>
        internal static string WebSiteIsDisable {
            get {
                return ResourceManager.GetString("WebSiteIsDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebSiteNews.
        /// </summary>
        internal static string WebSiteNews {
            get {
                return ResourceManager.GetString("WebSiteNews", resourceCulture);
            }
        }
    }
}
