//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Radyn.Reservation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Reservation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Reservation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Radyn.Reservation.Resources.Reservation", typeof(Reservation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Mode.
        /// </summary>
        public static string AmountMode {
            get {
                return ResourceManager.GetString("AmountMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error In Delete Hall.
        /// </summary>
        public static string ErrorInDeleteHall {
            get {
                return ResourceManager.GetString("ErrorInDeleteHall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error In Delete Hall Because It Has Child Hall.
        /// </summary>
        public static string ErrorInDeleteHallBecauseItHasChildHall {
            get {
                return ResourceManager.GetString("ErrorInDeleteHallBecauseItHasChildHall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error In Delete Hall Because It Has Rserved Chair.
        /// </summary>
        public static string ErrorInDeleteHallBecauseItHasRservedChair {
            get {
                return ResourceManager.GetString("ErrorInDeleteHallBecauseItHasRservedChair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error In Save Hall.
        /// </summary>
        public static string ErrorInSaveHall {
            get {
                return ResourceManager.GetString("ErrorInSaveHall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errror In Edit Hall Because It Has Reserved Chair.
        /// </summary>
        public static string ErrrorInEditHallBecauseItHasReservedChair {
            get {
                return ResourceManager.GetString("ErrrorInEditHallBecauseItHasReservedChair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall.
        /// </summary>
        public static string Hall {
            get {
                return ResourceManager.GetString("Hall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall Mode.
        /// </summary>
        public static string HallMode {
            get {
                return ResourceManager.GetString("HallMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotForSale.
        /// </summary>
        public static string NotForSale {
            get {
                return ResourceManager.GetString("NotForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Mode.
        /// </summary>
        public static string NumberMode {
            get {
                return ResourceManager.GetString("NumberMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved.
        /// </summary>
        public static string Reserved {
            get {
                return ResourceManager.GetString("Reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saled.
        /// </summary>
        public static string Saled {
            get {
                return ResourceManager.GetString("Saled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Mode.
        /// </summary>
        public static string StatusMode {
            get {
                return ResourceManager.GetString("StatusMode", resourceCulture);
            }
        }
    }
}
