
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE Common.Language ADD
	IsDefault bit NULL
GO
ALTER TABLE Common.Language SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
select Has_Perms_By_Name(N'Common.Language', 'Object', 'ALTER') as ALT_Per, Has_Perms_By_Name(N'Common.Language', 'Object', 'VIEW DEFINITION') as View_def_Per, Has_Perms_By_Name(N'Common.Language', 'Object', 'CONTROL') as Contr_Per 

go
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE Congress.[User] ADD
	Culture varchar(10) NULL
GO
ALTER TABLE Congress.[User] SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
select Has_Perms_By_Name(N'Congress.[User]', 'Object', 'ALTER') as ALT_Per, Has_Perms_By_Name(N'Congress.[User]', 'Object', 'VIEW DEFINITION') as View_def_Per, Has_Perms_By_Name(N'Congress.[User]', 'Object', 'CONTROL') as Contr_Per 
go

INSERT INTO [Security].[RadynConfig] (Name, Value) VALUES ('DbVersion', '3.0.0')

Go
